
CREATE DATABASE LISTA002;
USE LISTA002;
CREATE TABLE ALUNOS(
	CODIGO_ALUNO INT,
    NOME_ALUNO VARCHAR(50),
    TELEFONE_ALUNO VARCHAR(50),
    CIDADE_ALUNO VARCHAR(50)
    );
    DESC ALUNOS;
CREATE TABLE ALUNOS_2(
CODIGO_A2 INT,
NOME_A2 VARCHAR(200),
TELEFONE_A2 VARCHAR(50),
CIDADE_A2 VARCHAR(100)
);
CREATE TABLE FUNCIONARIOS(
NOME_F VARCHAR(100),
ENDERECO_F VARCHAR(200),
TELEFONE_F VARCHAR(50),
RG_F VARCHAR(50),
CPF_F CHAR(11),
SALARIO_F VARCHAR(50),
CIDADE_F VARCHAR(50),
ESTADO_F VARCHAR(50), 
CEP_F VARCHAR(50)
);
CREATE TABLE FORNECEDORES(
NOME_FOR VARCHAR(100),
ENDERECO_FOR VARCHAR(200),
TELEFONE_FOR VARCHAR(50),
CEP_FOR VARCHAR (50),
CNPJ_FOR VARCHAR(50),
E_MAIL_FOR VARCHAR(50),
CIDADE_FOR VARCHAR(50),
ESTADO_FOR VARCHAR(50)
);
CREATE TABLE LIVROS(
CODIGO_L INT,
NOME_L VARCHAR(200),
CATEGORIA_L VARCHAR(200),
SINOPSE_L VARCHAR(500),
CUSTO_LIVRO VARCHAR(50),
VALOR_VENDA VARCHAR(50)
);
DESC ALUNOS;

DESC ALUNOS_2;

DESC FORNECEDORES;

DESC FUNCIONARIOS;

DESC LIVROS;
CREATE TABLE ESTOQUE(
CODIGO_PRODUTO INT,
NOME_PRODUTO VARCHAR(50),
CATEGORIA_PRODUTO VARCHAR(50),
FORNECEDOR_PRODUTO VARCHAR(200),
QUANTIDADE_PRODUTO VARCHAR(50)
);
CREATE TABLE NOTAS(
CODIGO INT,
NOME_ALUNO VARCHAR(200),
BIMESTRE INT,
PERIODO INT
);
CREATE TABLE CAIXA(
CODIGO_TRANSACAO INT,
DATA_TRANSACAO DATE,
DESCRICAO VARCHAR(300),
DEBITO VARCHAR(200),
CREDITO VARCHAR(200)
);
CREATE TABLE CONTAS_A_PAGAR(
CODIGO_CONTA INT,
DATA_CONTA DATE,
DESCRICAO_CONTA VARCHAR(300),
VALOR_CONTA VARCHAR(50),
DATA_PAGAMENTO_CONTA DATE
);
CREATE TABLE CONTAS_A_RECEBER(
CODIGO_REC INT,
DATA_CONTA_REC DATE,
DESCRICAO_REC VARCHAR(300),
VALOR_REC VARCHAR(50),
DATA_REC DATE
);
CREATE TABLE FILMES(
CODIGO_FILME INT,
NOME_FILME VARCHAR(200),
SINOPSE_FILME VARCHAR(300),
GENERO_FILME VARCHAR(100)
);
CREATE TABLE CDS(
CODIGO_CD INT,
NOME_CD VARCHAR(200),
GENERO_MUSICAL VARCHAR(200),
ANO_CD INT,
ARTISTA_CD VARCHAR(200)
);
DROP TABLE ALUNOS_2;
DESC ALUNOS_2;
DROP TABLE LIVROS;
DROP TABLE CONTAS_A_PAGAR;
DROP TABLE CONTAS_A_RECEBER;
DROP TABLE FILMES;
DESC ALUNOS;
DESC CAIXA;
DESC ESTOQUE;
ALTER TABLE ALUNOS RENAME TO SUPER_ALUNOS;
DESC SUPER_ALUNOS;
ALTER TABLE ESTOQUE RENAME TO PRODUTOS;
ALTER TABLE NOTAS RENAME TO APROVADOS;
ALTER TABLE APROVADOS RENAME TO NOTAS;
-- A TABELA DINHEIRO NAO EXISTE;
DROP TABLE NOTAS;
ALTER TABLE SUPER_ALUNOS RENAME TO ALUNOS;
ALTER TABLE ALUNOS RENAME TO ESTUDANTES;
ALTER TABLE ESTUDANTES RENAME TO SUPER_ESTUDANTES;
DESC SUPER_ESTUDANTES;
DROP TABLE SUPER_ESTUDANTES;
DESC SUPER_ESTUDANTES;
DESC ALUNOS;
-- TABELA ALUNOS NAO EXISTE MAIS NO BANCO DE DADOS;
-- A TABELA CAIXA NAO FOI EXCLUIDA PARA SER RECRIADA;
ALTER TABLE CAIXA ADD OBSERVACAO VARCHAR(300);
-- A TABELA ALUNOS FOI EXCLUIDA;
DESC CAIXA;
ALTER TABLE CAIXA ADD SALDO VARCHAR(200);