CREATE DATABASE ELEICAO;

USE ELEICAO;

CREATE TABLE CARGO(
CODIGO_CARGO INT PRIMARY KEY UNIQUE NOT NULL,
NOME_CARGO VARCHAR(30) UNIQUE NOT NULL,
CHECK (NOME_CARGO <> 'PREFEITO' AND NOME_CARGO <> 'VEREADOR'),
SALARIO FLOAT NOT NULL DEFAULT '17000.00',
NUMERO_VAGAS INT UNIQUE NOT NULL
);

CREATE TABLE PARTIDO(
CODIGO_PARTIDO INT PRIMARY KEY UNIQUE NOT NULL,
SIGLA CHAR(5) UNIQUE NOT NULL,
NOME VARCHAR(40) UNIQUE NOT NULL, 
NUMERO INT UNIQUE NOT NULL
);

CREATE TABLE CANDIDATO(
NUMERO_CANDIDATO INT PRIMARY KEY UNIQUE NOT NULL,
NOME VARCHAR(40) UNIQUE NOT NULL,
CODIGO_CARGO INT NOT NULL,
CODIGO_PARTIDO INT NOT NULL,
CONSTRAINT FK_CANCAR FOREIGN KEY (CODIGO_CARGO) REFERENCES CARGO (CODIGO_CARGO),
CONSTRAINT FK_CANPAR FOREIGN KEY (CODIGO_PARTIDO) REFERENCES PARTIDO (CODIGO_PARTIDO)
);

CREATE TABLE VOTO(
TITULO_ELEITOR VARCHAR(30) PRIMARY KEY NOT NULL,
NUMERO_CANDIDATO INT NOT NULL,
CONSTRAINT FK_VOCAN FOREIGN KEY (NUMERO_CANDIDATO) REFERENCES CANDIDATO (NUMERO_CANDIDATO)
);

CREATE TABLE ELEITOR(
TITULO_ELEITOR VARCHAR(30) PRIMARY KEY NOT NULL,
ZONA_ELEITORAL CHAR(5) NOT NULL,
SESSAO_ELEITORAL CHAR(5) NOT NULL,
NOME VARCHAR(40) NOT NULL
);