CREATE DATABASE REVENDEDORA_CARROS;

USE REVENDEDORA_CARROS;

CREATE TABLE AUTOMOVEL(
RENAVAM INT PRIMARY KEY NOT NULL,
PLACA INT NOT NULL UNIQUE,
MARCA VARCHAR(30),
MODELO VARCHAR(20),
ANO_FABRICAÇAO INT,
ANO_MODELO INT,
COR VARCHAR (20),
MOTOR VARCHAR(20),
NUMERO_PORTAS INT,
TIPO_COMBUSTIVEL VARCHAR(30),
PRECO INT,
ID_COMPRA INT NOT NULL UNIQUE AUTO_INCREMENT
);

CREATE TABLE CLIENTES(
ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
ID_ENDERECO INT NOT NULL
);

CREATE TABLE ENDERECO_COMPLETO(
ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
RUA VARCHAR(50) NOT NULL,
NUMERO INT,
COMPLEMENTO VARCHAR(100),
BAIRRO VARCHAR(20),
CIDADE VARCHAR(100),
ESTADO VARCHAR(50),
CEP VARCHAR(8) NOT NULL
);

CREATE TABLE VENDEDORES(
CODIGO_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
SOBRENOME VARCHAR(50),
TELEFONE VARCHAR(20),
ID_ENDERECO INT NOT NULL,
DATA_ADMISSAO DATE,
SALARIO_FIXO INT
);

CREATE TABLE NEGOCIO(
ID_COMPRA INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
DATA_COMPRA DATE,
PRECO_PAGO INT,
RENAVAM INT NOT NULL, 
CODIGO_VENDEDOR INT,
ID_CLIENTE INT NOT NULL 
);

ALTER TABLE AUTOMOVEL ADD FOREIGN KEY (ID_COMPRA) REFERENCES NEGOCIO (ID_COMPRA);
ALTER TABLE CLIENTES ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO_COMPLETO (ID_ENDERECO);
ALTER TABLE VENDEDORES ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO_COMPLETO (ID_ENDERECO);

ALTER TABLE NEGOCIO ADD FOREIGN KEY (RENAVAM) REFERENCES AUTOMOVEL (RENAVAM);
ALTER TABLE NEGOCIO ADD FOREIGN KEY (CODIGO_VENDEDOR) REFERENCES VENDEDORES (CODIGO_VENDEDOR);
ALTER TABLE NEGOCIO ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);

DESCRIBE NEGOCIO;