CREATE DATABASE CLINICA;

USE CLINICA;

CREATE TABLE SALA (
SALA_ID SMALLINT PRIMARY KEY,
NUMERO_SALA INT UNIQUE NOT NULL CHECK(NUMERO_SALA > 1 AND NUMERO_SALA < 50),
ANDAR INT UNIQUE NOT NULL,
MEDICO_ID SMALLINT NOT NULL,
FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO(MEDICO_ID)
);

CREATE TABLE MEDICO (
MEDICO_ID SMALLINT PRIMARY KEY,
CRM VARCHAR(15) NOT NULL UNIQUE,
NOME VARCHAR(250) NOT NULL,
IDADE INT(100) NOT NULL,
ESPECIALIDADE CHAR(20),
CPF VARCHAR(15) NOT NULL,
DATA_DE_ADM DATE
);

CREATE TABLE PACIENTES(
ID_PACIENTES INT PRIMARY KEY AUTO_INCREMENT,
RG VARCHAR(15) UNIQUE NOT NULL,
NOME VARCHAR(40) NOT NULL,
DATA_NASCIMENTO DATE,
CIDADE CHAR(30) DEFAULT 'ITABUNA',
DOENCA VARCHAR(40) NOT NULL,
PLANO_SAUDE VARCHAR(40) NOT NULL DEFAULT 'SUS'
);

CREATE TABLE FUNCIONARIOS(
ID_FUNCIONARIOS INT PRIMARY KEY AUTO_INCREMENT,
MATRICULA VARCHAR(15) UNIQUE NOT NULL,
NOME VARCHAR(40) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
DATA_ADMISSAO DATE NOT NULL
);

ALTER TABLE FUNCIONARIOS ADD CARGO VARCHAR(40) NOT NULL DEFAULT 'ASSISTENTE MEDICO';
ALTER TABLE FUNCIONARIOS ADD SALARIO FLOAT NOT NULL DEFAULT '510.00';

CREATE TABLE CONSULTA(
CONSULTA_ID INT PRIMARY KEY,
PACIENTE_ID INT NOT NULL,
MEDICO_ID SMALLINT NOT NULL,
FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID),
FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO(MEDICO_ID)
);

ALTER TABLE SALA ADD ID_MEDICOS INT;

ALTER TABLE SALA ADD CONSTRAINT FK_SALMED FOREIGN KEY (ID_MEDICOS) REFERENCES MEDICOS(ID_MEDICOS);

ALTER TABLE CONSULTAS ADD ID_MEDICOS INT;

ALTER TABLE CONSULTAS
ADD CONSTRAINT FK_CONSMED FOREIGN KEY (ID_MEDICOS) REFERENCES MEDICOS (ID_MEDICOS);

ALTER TABLE CONSULTAS ADD ID_PACIENTES INT;

ALTER TABLE CONSULTAS
ADD CONSTRAINT FK_CONSPAC FOREIGN KEY (ID_PACIENTES) REFERENCES PACIENTES (ID_PACIENTES);